services:
  ModelRouter:
    #image: ghcr.io/macedot/modelrouter:latest
    build: .
    container_name: ModelRouter
    restart: unless-stopped
    ports:
      - "12345:12345"
    volumes:
      - /root/.config/ModelRouter/ModelRouter.json:/app/ModelRouter.json:ro
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:12345/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
